FROM debian:buster-slim AS builder
LABEL maintainer="mats@viacard.com"

RUN apt-get update -y > /dev/null
RUN apt-get install -y curl bzip2 git make > /dev/null
RUN rm -rf /var/lib/apt/lists/*
RUN useradd -ms /bin/bash maker

RUN \
 curl -L "https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2?revision=c34d758a-be0c-476e-a2de-af8c6e16a8a2?product=GNU-RM%20Downloads,64-bit,,Linux,8-2019-q3-update" | \
 tar xj -C /usr/local/bin/
 
ADD arm.tar.bz2 /usr/local/include/

#---------------------------------------------------------
FROM scratch 
COPY --from=builder / /

ARG proctype
ARG proctypelc

ENV PATH="${PATH}:/usr/local/bin/gcc-arm-none-eabi-8-2019-q3-update/bin/"
ENV CCPATH=/usr/local/bin/gcc-arm-none-eabi-8-2019-q3-update/bin
ENV INC1=/usr/local/include/arm/cmsis/5.0.1/CMSIS/Include
ENV INC2=/usr/local/include/atmel/${proctype}_DFP/1.2.91/${proctypelc}/include
COPY atmel/${proctype}_DFP/* /usr/local/include/atmel/${proctype}_DFP/

USER maker
WORKDIR /home/maker
VOLUME ["/home/maker"]

